CREATE TABLE servers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  ip_address VARCHAR(255) NOT NULL,
  status TINYINT NOT NULL,
  cpu_usage FLOAT NULL,
  memory_usage FLOAT NULL,
  last_checked DATETIME NULL,
  is_monitored TINYINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL
);